plugins {
	id 'java'
	id 'org.springframework.boot' version '3.2.0'
	id 'io.spring.dependency-management' version '1.1.4'
}

group = 'com.booking.auth'
version = '1.0.0'

java {
	sourceCompatibility = '17'
}

configurations {
	compileOnly {
		extendsFrom annotationProcessor
	}
}

repositories {
	mavenCentral()
}

dependencies {
	// Spring Boot Web
	implementation 'org.springframework.boot:spring-boot-starter-web'
	
	// Spring Boot Data JPA
	implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
	
	// Spring Boot Security
	implementation 'org.springframework.boot:spring-boot-starter-security'
	
	// Spring Authorization Server
	implementation 'org.springframework.boot:spring-boot-starter-oauth2-authorization-server'
	
	// Validation
	implementation 'org.springframework.boot:spring-boot-starter-validation'
	
	// Support for .env files
	implementation 'me.paulschwarz:spring-dotenv:4.0.0'
	
	// Database Driver (MySQL)
	runtimeOnly 'com.mysql:mysql-connector-j'
	
	// Lombok
	compileOnly 'org.projectlombok:lombok'
	annotationProcessor 'org.projectlombok:lombok'
	
	// Test
	testImplementation 'org.springframework.boot:spring-boot-starter-test'
	testImplementation 'org.springframework.security:spring-security-test'
}

tasks.named('test') {
	useJUnitPlatform()
}
